### ISSUE TITLE
[NumberGuesser] default

### ISSUE THREAD

**Issue by pavel-b-novikov** [TroProCho/nsudotnet#1]
``` C#
 _nickname = default (string);
_historyAnswer = default (List<int>);
_guessesNumber = default (int);
```

Что делает default и в особенности - что он делает здесь?

**Comment by TroProCho** [comment]
Присваивает null и нули переменным

**Comment by TroProCho** [comment]
default назначает переменной типа Т значение по умолчанию. Применяется в шаблона. Здесь, у меня, его приминение излишне. Убрал.

**Comment by pavel-b-novikov** [comment]
Молодец, хвалю.
