### ISSUE TITLE
[NumberGuesser] Константы

### ISSUE THREAD

**Issue by pavel-b-novikov** [TroProCho/nsudotnet#2]
Я вижу у вас много констант.
А какие типы могут быть объявлены константами?

**Comment by TroProCho** [comment]
Числовые типы, bool, string, enum

**Comment by pavel-b-novikov** [comment]
А почему не DateTime?

**Comment by TroProCho** [comment]
Да чето как и другие структуры не получается его константой сделать.

**Comment by pavel-b-novikov** [comment]
Enum компилятором тоже преобразуется в структуру так-то

**Comment by TroProCho** [comment]
Вообщем константой можно обозвать то, что можно определить на этапе компиляции. То что нельзя сказать про DateTime. А вот с числовыми типами и bool (узнал и наконец запомнил что это struct, моя жизнь не будет прежней), string и enum все нормально в этом плане.

**Comment by pavel-b-novikov** [comment]
А вот в VB.NET, который компилируется в тот же IL-код, сделать DateTime константой можно!

**Comment by TroProCho** [comment]
Да там своя жесть вообще твориться.
Взято с просторов мсдна
https://msdn.microsoft.com/ru-ru/library/cyxe49xw.aspx
initializer - Обязательный. Выражение, вычисляемое во время компиляции и присваиваемое константе.
При определении константы с типом данных Object компилятор Visual Basic предоставляет ей тип initializer вместо Object.

А там можно подобную конструкцию написать const int a = (new Random()).Next();  ?

**Comment by pavel-b-novikov** [comment]
неа

**Comment by pavel-b-novikov** [comment]
Подсказка: если бы в js были константы, то регекс можно было бы сделать константой.

**Comment by TroProCho** [comment]
"Важный нюанс: в C# для констант можно использовать только базовые типы (например, int) и строки. Это необходимо потому, что подобное поле не будет существовать на самом деле, вместо этого, везде, где оно используется, будут подставлены значения этого поля."
#не_моё

**Comment by pavel-b-novikov** [comment]
Ладно. Видимо вы сами не догадаетесь.
Литеральные типы. Литеральные типы можно использовать как константы - типы, состояние которых полностью описывается строкой кода (терминальным символом, если у вас была теория трансляции и компиляции). Здесь небольшой хак-workaround составляют Enum-ы, ибо не могут быть интерпретированы как литерал, ибо являют собой MemberAccessExpression, но на этот случай у компилятора есть свитч.
