### ISSUE TITLE
[Enigma] Ресурсы

### ISSUE THREAD

**Issue by pavel-b-novikov** [TroProCho/nsudotnet#3]
Оффтоп: вот за это прям пятюня. Отличное решение. Порадовали старика.

``` C#
SupportedAlgorithms supportedAlgorithm;
            if (!SupportedAlgorithms.TryParse(args[2], true, out supportedAlgorithm))
```

Перенесите все константные строки в ресурсы, пожалуйста.

**Comment by TroProCho** [comment]
В смысле от enum класса избавиться?

**Comment by TroProCho** [comment]
Перенес константные строки в ресурсы

**Comment by pavel-b-novikov** [comment]
Не, не. Это не сарказм, это я вас реально похвалил. Мне лично в голову не пришло так сделать.
